### ISSUE TITLE
Invalid VolumeID: error decoding volume ID (failed to decode CSI identifier, string underflow)

### ISSUE THREAD

**Issue by JWebDev** [csi-addons/kubernetes-csi-addons#615]
Hi,
I have a Ceph cluster, I want to clean up unnecessary files from time to time.

I have configured everything as described in the documentation. 
https://github.com/csi-addons/kubernetes-csi-addons/blob/v0.8.0/docs/deploy-controller.md#installation-for-versioned-deployments

https://github.com/csi-addons/kubernetes-csi-addons/blob/v0.8.0/docs/reclaimspace.md#reclaimspacecronjob
reclaimspacecronjob:
```
apiVersion: csiaddons.openshift.io/v1alpha1
kind: ReclaimSpaceCronJob
metadata:
  name: reclaimspace-mongo
  namespace: mongo
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backOffLimit: 6
      retryDeadlineSeconds: 600
      timeout: 3600
      target:
        persistentVolumeClaim: mongo
  schedule: '@hourly'
  successfulJobsHistoryLimit: 5
```

The controller works, finds all possible PVCs and their statuses.
CronJob triggers and is in mongo namespace.

My PVC and PV have the same names - mongo.

This is what my StorageClass looks like
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-block-retain
provisioner: rook-ceph.rbd.csi.ceph.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: '2'
  pool: app
---
```

This is how the rbd was created: `rbd create --size 1024000 app/mongo`

**CSI controller is not finding the mysql PV. But it exists, I can see it in the PVs list.**

Here is the log from the controller.
```
2024-07-15T02:12:05.074Z	ERROR	Failed to make controller request	{"controller": "reclaimspacejob", "controllerGroup": "csiaddons.openshift.io", "controllerKind": "ReclaimSpaceJob", "ReclaimSpaceJob": {"name":"reclaimspace-mongo-1721009520","namespace":"mongo"}, "namespace": "mongo", "name": "reclaimspace-mongo-1721009520", "reconcileID": "ed1dc2d7-1e9f-415d-8a44-cd6be76308fe", "PVCName": "mongo", "PVCNamespace": "mongo", "PVName": "mongo", "NodeID": "app-worker1", "Timeout": "1h0m0s", "nodeClient": "rook-ceph/csi-rbdplugin-7zj59", "error": "rpc error: code = Aborted desc = failed to find volume with ID \"mongo\": invalid VolumeID: error decoding volume ID (failed to decode CSI identifier, string underflow) (mongo)"}
```
